language: node_js

node_js:
  - "7"

cache: yarn

jobs:
  include:
    - script: yarn e2e
    - script: yarn flow
    - script: yarn lint
    - script: yarn prettier
    - script: yarn test
    - stage: deploy to production
      install: npm install -g now now-purge
      script: skip
      deploy:
        provider: script
        script: now-purge t $NOW_TOKEN && now -t $NOW_TOKEN --alias
        on:
          branch: master
