export const maxWidth = '634px'
export const navbarHeight = '66px'
export const headerHeight = '62vh'
export const avatarSize = '7vh'
//export const minAvatarSize = '128px'
export const minAvatarSize = '13.671vh'
